#+TITLE: Org bootstrap document
#+AUTHOR: Lars Tveito
#+OPTIONS: toc:2 num:nil H:4 tex:imagemagick
#+HTML_HEAD: <meta name="viewport" content="width=device-width, initial-scale=1"/>
#+HTML_HEAD: <link type="text/css" rel="stylesheet" href="css/bootstrap.min.css" />
#+HTML_HEAD: <link rel="stylesheet" type="text/css" href="css/style.css" />
#+HTML_HEAD: <script type="text/javascript" src="js/jquery-2.1.3.min.js"></script>
#+HTML_HEAD: <script type="text/javascript" src="js/jquery-ui.min.js"></script>
#+HTML_HEAD: <script type="text/javascript" src="js/jquery.tocify.min.js"></script>
#+HTML_HEAD: <script type="text/javascript" src="js/bootstrap.min.js"></script>
#+HTML_HEAD: <script type="text/javascript" src="js/org-bootstrap.js"></script>

* About

  This is a simple scheme for Org mode to generate nice and readable HTML
  sites. Here are some examples of sites that uses this scheme (all in
  Norwegian):

  - [[http://folk.uio.no/larstvei/inf2810/v15/][INF2810 - Gruppelærerenes side]]
  - [[http://folk.uio.no/larstvei/inf2810/v15/emacs-setup.html][Scheme i Emacs!]]
  - [[http://folk.uio.no/larstvei/inf2810/v15/veien-til-vakker-scheme.html][Veien Til Vakker Scheme]]

* Usage

  The scheme consists of a series of CSS and JavaScript files located in the
  ~css~ and ~js~ directory. To use it, simply include the lines starting
  with ~#+OPTIONS:~ and ~#+HTML_HEAD:~ in the top of this file in an ~.org~
  file. It assumes that the ~.org~ file is located in a directory like this
  repository, containing the ~css~ and ~js~ directories.

  If these conditions are met, one should be able to export the ~.org~ file
  to HTML using the ~org-html-export-to-html~ command, accessible by the key
  sequence ~C-c C-e h h~.

* License

  The MIT License (MIT)

  Copyright (c) 2015 Lars Tveito

  Permission is hereby granted, free of charge, to any person obtaining a copy
  of this software and associated documentation files (the "Software"), to deal
  in the Software without restriction, including without limitation the rights
  to use, copy, modify, merge, publish, distribute, sublicense, and/or sell
  copies of the Software, and to permit persons to whom the Software is
  furnished to do so, subject to the following conditions:

  The above copyright notice and this permission notice shall be included in all
  copies or substantial portions of the Software.

  THE SOFTWARE IS PROVIDED "AS IS", WITHOUT WARRANTY OF ANY KIND, EXPRESS OR
  IMPLIED, INCLUDING BUT NOT LIMITED TO THE WARRANTIES OF MERCHANTABILITY,
  FITNESS FOR A PARTICULAR PURPOSE AND NONINFRINGEMENT. IN NO EVENT SHALL THE
  AUTHORS OR COPYRIGHT HOLDERS BE LIABLE FOR ANY CLAIM, DAMAGES OR OTHER
  LIABILITY, WHETHER IN AN ACTION OF CONTRACT, TORT OR OTHERWISE, ARISING FROM,
  OUT OF OR IN CONNECTION WITH THE SOFTWARE OR THE USE OR OTHER DEALINGS IN THE
  SOFTWARE.
